### ISSUE TITLE
Does not send packets

### ISSUE THREAD

**Issue by zHadsaw** [gamemann/Packet-Flooder#1]
It shows that it is sending, but in reality nothing arrives at the destination machine.

**Comment by gamemann** [comment]
Hey,

Would you be able to provide the command line usage you're using? I just setup a vanilla VM and tested the program on it. I had no issues sending packets outbound.

With that said, I'd recommend running `tcpdump` on the machine you're sending packets from to see if it shows any of the outbound packets.

Additionally, what Linux distro and kernel are you running? You can get the kernel by executing `uname -r`.

**Comment by gamemann** [comment]
I'm going to close this for now due to no response. If you continue having issues, please let me know!
